name: CI

on:
  push:
    branches: [ main ]
    # tags:
    #   - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r20b
        add-to-path: false

    - uses: actions/checkout@v3

    - name: Build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        sh build.sh
        ls -l build/*

    - name: Upload Linux
      uses: svenstaro/upload-release-action@v2
      with:
        file: build/gts-amd64
        body: "Linux"
