name: CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: |
        sh build.sh
        ls -l build/*

    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        sudo apt-get install -y jq
        GIT_TAG=`echo $GITHUB_REF | sed 's/refs\/tags\///'`
        # get upload url
        API_UPLOAD_URL=`curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
        -d '{"tag_name":"'${GIT_TAG}'"}' \
        | jq --raw-output '.upload_url' \
        | sed 's/{?name,label}/?name/'`
        # upload
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary @'build/gts-amd64' \
        ${API_UPLOAD_URL}=gts-amd64
        # upload
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary @'build/gts-amd64.exe' \
        ${API_UPLOAD_URL}=gts-amd64.exe
        # upload
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary @'build/gts-android_arm64' \
        ${API_UPLOAD_URL}=gts-android_arm64
        # upload
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Content-Type: application/octet-stream" \
        --data-binary @'build/android.aar' \
        ${API_UPLOAD_URL}=android.aar
