name: CI

on:
  push:
    # branches: [ main ]
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
        cache: false
    
    - name: check-go
      run: go version

    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        # cache: 'gradle'
    
    - name: check-java
      run: java --version

    - id: ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r20b
        add-to-path: false

    - uses: actions/checkout@v3

    - name: Build
      env:
        ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
      run: |
        sh build.sh
        ls -l build/*

      #    # 上传构建产物
      #    - uses: actions/upload-artifact@v3
      #      with:
      #        name: lilu
      #        path: build/

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: build/gts-*
        overwrite: true
        body: "里路好传服务, 目前支持Ubuntu, Windows, Android. 访问 https://lilu.red 探索更多有趣的技术."
